### ISSUE TITLE
Browser doesn't properly interpret CSS

### ISSUE THREAD

**Issue by Jed-Giblin** [swaggo/buffalo-swagger#1]
When using this library, I noticed that my swagger-ui.css wasn't being loaded, so the entire page was being loaded with no style.

Looking in the developer tools of Chrome and using both the error console and the Network tab, I found the following:
1. The browser can properly request the file ( So the HTML template works )
2. The server can serve the file ( So the web server code works )
3. The response from the webserver has a content-type of: "text/plain"  ( The issue )

The response when requesting a stylesheet should be { "Content-Type":"text/css" } which is usually covered because your stylesheets are typically in some other directory. 

I've opened a simple PR to fix this and was able to validate that this resolved the issue and the page loads with style now.

**Comment by divan** [comment]
Save happens with JS.
```
[Error] Refused to execute https://.../apidocs/swagger-ui-bundle.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
[Error] Refused to execute https://.../apidocs/swagger-ui-standalone-preset.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
